export const READER = {
  MAX_TEXT_WIDTH_PX: 1200,
  CFI_GENERATION_POINTS: 150,
  TOC_MIN_WIDTH_EM: 10,
  TOC_MAX_WIDTH_PCT: 0.6,
  TOC_ITEM_BASE_PAD_PX: 12,
  TOC_ITEM_DEPTH_STEP_PX: 16,
} as const;
